name: publish-icons
on:
  push:
    branches:
    - 'master'
    paths:
    - 'package.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
        scope: '@rancher'        
    - name: script
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}        
      run: |
        git config --global user.name 'Rancher Icons'
        git config --global user.email 'noreply@rancher.com'
        yarn install
        yarn run upload -i -f
